- name: Installation of packages for Nagios
  tags: dependecies, libraries
  dnf:
    name:
      - python2-pip
      - openssl-devel
      - httpd
      - php
      - gcc
      - glibc
      - glibc-common
      - perl
      - wget
      - gd-devel
      - gd
      - make
      - gettext
      - automake
      - autoconf
      - net-snmp
      - net-snmp-utils
    state: latest
    update_cache: yes

- name: Installing the passlib python package
  pip:
    name: passlib

- name: Creating directory for the download files
  file:
    path: ~/nagios
    state: directory

- name: Installation and extraction of Nagios
  unarchive:
    src: https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.6.tar.gz
    dest: ~/nagios
    remote_src: yes
    mode: 0777
    owner: root
    group:

- name: Compiling, Installing, and Creating users and group for Nagios
  shell: |
    cd ~/nagios/nagioscore-**
    ./configure
    make all
    make install-groups-users
    usermod -a -G nagios apache
    make install
    make install-daemoninit
    make install-commandmode
    make install-config
    make install-webconf

- name: Installation of Nagios plugins and then extracting it
  unarchive:
    src: https://github.com/nagios-plugins/nagios-plugins/archive/release-2.3.3.tar.gz
    dest: ~/nagios
    remote_src: yes
    mode: 0777
    owner: root
    group: root

- name: Compiling and Installing Nagios plugins
  shell: |
    cd ~/nagios/nagios-plugins*
    ./tools/setup
    ./configure
    make
    make install

- name: Adding the User to password file
  community.general.htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: bolivar_nagi
    password: 12345

- name: Starting and Restarting of Nagios
  service:
    name: httpd
    state: restarted
    enabled: true
