---
- hosts: all
  become: true
  vars:
    UserName_01: ManageNode_Ubuntu
    UserName_02: ManageNode_CentOS

  tasks:

  - name: MOTD
    template:
      src: msg.j2
      dest: /etc/motd
    tags:
      - motd_config

  - name: UserName_01 - Ubuntu
    ansible.builtin.user:
      name: "{{ UserName_01 }}"
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: Installation of latest python3 and pip3 for Ubuntu
    apt:
      name:
        - python3
        - python3-pip
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Installation of Java open-jdk for Ubuntu
    apt:
      name: default-jdk
    when: ansible_distribution == "Ubuntu"

  - name: UserName_02 - CentOS
    ansible.builtin.user:
      name: "{{ UserName_02 }}"
      state: present
    when: ansible_distribution == "CentOS"

  - name: Installation of latest python3 and pip3 for CentOS
    dnf:
      name:
        - python3
        - python3-pip
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Installation of Java open-jdk for CentOS
    dnf:
      name: java-11-openjdk-devel
    when: ansible_distribution == "CentOS"

  - name: Use python3 as a default python for CentOS
    ansible.builtin.command: alias python3=/usr/bin/python3
    when: ansible_distribution == "CentOS"

  - name: Use pip3 as default pip for CentOS
    ansible.builtin.command: alias pip3=/usr/bin/pip
    when: ansible_distribution == "CentOS"




